### PR TITLE
Increase refresh rate

### PR DESCRIPTION
**Pull request by GSzabados**
Increase refresh rate

### CODE REVIEW

**Comment by GSzabados** [comment]
I use this way since I installed from the Home Assistant commit and works well.
`
        track_utc_time_change(hass, lambda now: self._refresh(), second=range(0, 60, 30))`

**Comment by simontb** [comment]
Thanks for submitting this and the other pull requests. I'm not sure whether this one should be merged. I feel pulling every 30 seconds might be abusive use of the Mojio API.

When I developed the integration I thought about the refresh rate needed for my automation scenarios and concluded that 5 minutes is sufficient. My scenario was to detect when I start driving home from work (30 minutes drive) and the pre-heat/cool my flat. For the 30 minutes drive, the exact moment I leave isn't that important and also I don't need to precisely track my car. However, I'm aware that this might be different with other use cases.

I think what we could do is to have the refresh rate configurable (in reasonable ranges), so the user can decide what's best. IMHO it shouldn't be possible to refresh more frequently than every 30 seconds, but a sensible maximum might be 10 or even 30 minutes.

What do you think and why is it important that you need the higher refresh rate?

**Comment by GSzabados** [comment]
I am using the component to track the car and keep a local record where it was. I do not like to rely on cloud services and their retention periods.

I copied that code from the FleetGo integration.

It can be set a 1 per minute as I can remember that is the native refresh rate of the dongle and the App as well.

From previous experience I know that even 1 minute can be not enough as some maneuvers are not recorded correctly. I had a funny situation with a coworker years ago, when we both started from the same place, myself as second, and arrived before the coworker to the office.  Of course the coworker couldn't believe what has happened and looked at the tracking data of the cars and couldn't find it out where I did a different turn or have I done any over speeding (I didn't). Actually the distance what we did was about 1.5 km in a small town and the 1 minute logging was enough to hide the real route.

Anyhow, the 1 minute update should be enough for this...

**Comment by simontb** [comment]
This is now implemented in #15.

From my point of view this fulfills your requirement. Thus, I'll close this PR. Feel free to open a new one or an issue should you have further requirements.

**Pull request closed without merging**
